import { v4 } from 'uuid'
const tasks = [
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '03:25',
        taskCategory: 'Testing',
        taskDescription: 'Environment configuration',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '01:30',
        taskCategory: 'Development',
        taskDescription: 'Code Review',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '00:15',
        taskCategory: 'Other',
        taskDescription: 'Other',
        comments: 'Ticket #234, solve the problem',
        overtime: true,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '01:30',
        taskCategory: 'Meetings (Internal)',
        taskDescription: '1:1 meeting with Manager',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '00:45',
        taskCategory: 'Development',
        taskDescription: 'Backlog refinement meeting',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '02:00',
        taskCategory: 'Idle time',
        taskDescription: 'No assigned tasks',
        comments: 'Ticket #234, solve the problem',
        overtime: true,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '03:25',
        taskCategory: 'Testing',
        taskDescription: 'Environment configuration',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '01:30',
        taskCategory: 'Development',
        taskDescription: 'Code Review',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '00:15',
        taskCategory: 'Other',
        taskDescription: 'Other',
        comments: 'Ticket #234, solve the problem',
        overtime: true,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '01:30',
        taskCategory: 'Meetings (Internal)',
        taskDescription: '1:1 meeting with Manager',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '00:45',
        taskCategory: 'Development',
        taskDescription: 'Backlog refinement meeting',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '02:00',
        taskCategory: 'Idle time',
        taskDescription: 'No assigned tasks',
        comments: 'Ticket #234, solve the problem',
        overtime: true,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '03:25',
        taskCategory: 'Testing',
        taskDescription: 'Environment configuration',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '01:30',
        taskCategory: 'Development',
        taskDescription: 'Code Review',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '00:15',
        taskCategory: 'Other',
        taskDescription: 'Other',
        comments: 'Ticket #234, solve the problem',
        overtime: true,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 1,
        },
        hours: '01:30',
        taskCategory: 'Meetings (Internal)',
        taskDescription: '1:1 meeting with Manager',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 2,
        },
        hours: '00:45',
        taskCategory: 'Development',
        taskDescription: 'Backlog refinement meeting',
        comments: 'Ticket #234, solve the problem',
        overtime: false,
    },
    {
        id: v4(),
        date: new Date('2021-06-28'),
        project: {
            id: 2,
        },
        hours: '02:00',
        taskCategory: 'Idle time',
        taskDescription: 'No assigned tasks',
        comments: 'Ticket #234, solve the problem',
        overtime: true,
    },
]

export default tasks
